Add custom script support #46
gocd/docker-gocd-server pull request #54
Opened 2017-11-19 07:10 UTC by ketan

2017-11-19 09:59 UTC, ketan commented
@varshavaradarajan — if you're on board with this change, I can apply custom script support to the docker-gocd-agent repo as well.

2017-11-20 03:40 UTC, varshavaradarajan requested changes

2017-11-20 03:40 UTC, varshavaradarajan commented on README.md.erb
> +To install plugins, just add an ENV variable with the prefix `GOCD_PLUING_INSTALL_` and your name as `suffix`
PLUING => PLUGIN

2017-11-20 03:40 UTC, varshavaradarajan commented on install-gocd-plugins
> +GOCD_PLUGIN_EXTERNAL_HOME=${GOCD_PLUGIN_EXTERNAL_HOME:-/godata/plugins/external}
GOCD_PLUGIN_EXTERNAL_HOME - Can you please explain the comment about why we provide this when the go server will always look in /godata/plugins/external ? From the SystemEnvironment, I see that the external path is set as a system property.

2017-11-20 03:40 UTC, varshavaradarajan commented on Dockerfile
> +COPY install-gocd-plugins /usr/local/sbin/install-gocd-plugins
This should be in Dockerfile.erb

2017-11-20 10:43 UTC, varshavaradarajan commented on install-gocd-plugins
> +PLUGIN_ENV_NAMES=( "$(compgen -A variable GOCD_PLUGIN_INSTALL_)" )
compgen returns empty when I do `docker run -e GOCD_PLUGIN_INSTALL_github-pr=...`

2017-11-20 11:03 UTC, ketan commented
Which OS and bash version is this?

On Mon, Nov 20, 2017, 4:13 PM Varsha Varadarajan <notifications@github.com>
wrote:

> *@varshavaradarajan* commented on this pull request.
> ------------------------------
>
> In install-gocd-plugins
> <https://github.com/gocd/docker-gocd-server/pull/54#discussion_r151955321>
> :
>
> > @@ -0,0 +1,32 @@
> +#!/usr/bin/env bash
> +
> +yell() { echo "$0: $*" >&2; }
> +die() { yell "$*"; exit 111; }
> +try() { echo "$ $@" 1>&2; "$@" || die "cannot $*"; }
> +
> +GOCD_PLUGIN_EXTERNAL_HOME="/godata/plugins/external"
> +
> +if [ ! -e "${GOCD_PLUGIN_EXTERNAL_HOME}" ]; then
> +  try mkdir -p "${GOCD_PLUGIN_EXTERNAL_HOME}"
> +  try chown go:go "${GOCD_PLUGIN_EXTERNAL_HOME}"
> +fi
> +
> +# List all vars beginning with `GOCD_PLUGIN_INSTALL_`
> +PLUGIN_ENV_NAMES=( "$(compgen -A variable GOCD_PLUGIN_INSTALL_)" )
>
> compgen returns empty when I do docker run -e
> GOCD_PLUGIN_INSTALL_github-pr=...
>
> —
> You are receiving this because you authored the thread.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/gocd/docker-gocd-server/pull/54#pullrequestreview-77741495>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAApZvUjHEl-RaVUY467e2eQleN5xHeeks5s4VfHgaJpZM4QjSG6>
> .
>

2017-11-20 11:07 UTC, varshavaradarajan commented
Alpine 3.6, Bash 4.3.48-r1

2017-11-21 04:18 UTC, varshavaradarajan requested changes

2017-11-21 04:18 UTC, varshavaradarajan commented on install-gocd-plugins
> +    plugin_name="${env_var//GOCD_PLUGIN_INSTALL_/}"
env_var => name

2017-11-22 07:33 UTC, merged