Update document
gocd/docker-gocd-server pull request #8
Opened 2017-03-24 22:16 UTC by neofob

README.md:
* Add section on download/build docker image
* Tidy up markdown

Signed-off-by: Tuan T. Pham <tuan@vt.edu>

2017-03-30 03:18 UTC, varshavaradarajan requested changes

2017-03-30 03:18 UTC, varshavaradarajan commented on README.md
> +docker pull gocd/gocd-server:latest
We do not publish the `latest`. Our tags on dockerhub will be of the format `v<version>` where version refers to the GoCD version, like this `v17.3.0`

2017-03-30 03:18 UTC, varshavaradarajan commented on README.md
> +docker run -d -p8153:8153 -p8154:8154 gocd/gocd-server:latest
Same as above

2017-03-30 03:18 UTC, varshavaradarajan commented on README.md
>  docker run -v /path/to/godata:/godata -v /path/to/home-dir:/home/go gocd/gocd-server
Can you also point to the tag, since `latest` is not available

2017-03-30 03:18 UTC, varshavaradarajan commented on README.md
>  docker run -e GO_SERVER_SYSTEM_PROPERTIES="-Xmx4096mb -Dfoo=bar" gocd/gocd-server
Same as above

2017-03-31 17:43 UTC, neofob commented
I updated the change as requested.

2017-03-31 17:50 UTC, merged